### ISSUE TITLE
Change Readme information about generating access token 

### ISSUE THREAD

**Issue by speaktoalvin** [winterbe/github-matrix#1]
As you know that there are no Applications section in Github. In order to generate Access Tokens we have to go to "Personal access tokens" section and then we have to click on "Generate New Access Token". So the whole sentence should look like this.

You have to create your own GitHub API Token. Go to your **"GitHub Account Settings"**, choose **"Personal access tokens"** then click **"Generate New Token"**. Make sure you don't accidentally push your API token to GitHub (as I did in the past). Alternatively just pass the token as system property: java ... -DapiToken=YOUR_API_TOKEN

**Comment by winterbe** [comment]
The GitHub UI has changed since I wrote this project 2 years ago. Thanks for hint, I'll about the docs.
